name: Documentation

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy_docs:
    name: Build and deploy docs to GitHub Pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade-strategy eager -e .[docs]
        
    - name: Build the docs
      run: (cd docs && make html)
        
    - name: Deploy docs to GitHub Pages
      # Only deploy on new version
      if: startsWith(github.event.ref, 'refs/tags/v')
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book/_build/html  # sphinx output dir
