# This is a basic workflow to help you get started with Actions

name: Testing and coverage

# Controls when the action will run. 
on:
  # Triggers the workflow on push events for the main branch
  push:
    branches: [ main ]
  pull_request: # And on all Pull Requests
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-with-cov:
    runs-on: ubuntu-16.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.6.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e .[testing]

      - name: Run pytest with coverage
        run: |
          pytest --cov=test-package --cov-report=xml --cov-report=term-missing
          coverage xml
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: test-packge-pytests-py3.6.3
          flags: pytests
          file: ./coverage.xml
          fail_ci_if_error: true
